### PR TITLE
Update plugin Akismet to v3.3

### PR DESCRIPTION
**Pull request by ryanjbonnell**
This pull request updates Akismet to the latest release, version 3.3 (23 February 2017).

https://wordpress.org/plugins/akismet/

---

When creating a new site at Pantheon and logging into the WordPress Dashboard, users are greeted with an up-to-date installation of WordPress core, but all of the bundled Plugins and Themes are severely outdated.

This isn't a confidence inspiring welcome experience, as depicted in the following screenshot showing all of the available updates:

wordpress-updates

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> This pull request updates Akismet to the latest release, version 3.3 (23 February 2017).

Historically, the bundled plugins and themes haven't been updated because doing so has the potential for causing a merge conflict with existing Pantheon sites.

> When creating a new site at Pantheon and logging into the WordPress Dashboard, users are greeted with an up-to-date installation of WordPress core, but all of the bundled Plugins and Themes are severely outdated.

It seems feasible to me to call `wp plugin update --all` `wp theme update --all` when a new site is provisioned though, and commit those changes as the first commit on the downstream.

**Comment by ryanjbonnell** [comment]
> It seems feasible to me to call wp plugin update --all wp theme update --all when a new site is provisioned though, and commit those changes as the first commit on the downstream.

I think this is a great approach, as it would safely address the issue for _new sites_ without any raising any concern for pre-existing sites.

While this may improve future installations -- if this idea is adopted -- it doesn't address current sites.

> Historically, the bundled plugins and themes haven't been updated because doing so has the potential for causing a merge conflict with existing Pantheon sites.

Knowing that background does help clarify why Plugin and Theme updates seem to have been neglected by Pantheon.

Does Pantheon have an official recommendation on how core Plugins and Themes should be updated?

**Comment by greg-1-anderson** [comment]
The instructions on updating WordPress themes is a little buried in the [More Ways of Managing Code in SFTP Mode](https://pantheon.io/docs/more-sftp/) document.

Automatically updating plugins during provision is a good idea. See also [Advanced WordPress on Pantheon](https://github.com/ataylorme/Advanced-WordPress-on-Pantheon), which is a site template that includes visual regression tests to help with testing updates.

**Comment by ataylorme** [comment]
> See also Advanced WordPress on Pantheon, which is a site template that includes visual regression tests to help with testing updates

@greg-1-anderson that's actually the [WordPress at Scale Auto Update Repo](https://github.com/ataylorme/wordpress-at-scale-auto-update). There's [a blog post](https://pantheon.io/blog/automating-security-updates-scalewpio) as well.

**Comment by greg-1-anderson** [comment]
Thanks for the correction!

**Pull request closed without merging**
