### PR TITLE
Flush the WordPress object cache when flushing an entire site

### PR DESCRIPTION
**Pull request by danielbachhuber**
See https://github.com/pantheon-systems/wp-redis/issues/72

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@joshkoenig #reviewmerge

**Comment by joshkoenig** [comment]
This looks good. I'm wondering more and more about whether that `wp_redirect` really belongs there, but we can address this separately.

I don't think we need to make a special release for this, but we should roll it into the next upstream update.

**Comment by danielbachhuber** [comment]
> I don't think we need to make a special release for this, but we should roll it into the next upstream update.

@joshkoenig Is a PR against master fine for this, or is there something else you'd like me to do?

**Comment by joshkoenig** [comment]
This is fine. We just need to make sure we remember (paging @greg-1-anderson...) to merge this in with the next upstream release.

**Comment by greg-1-anderson** [comment]
Fixed in #72.

**Pull request closed without merging**
