### PR TITLE
remove line to contact support

### PR DESCRIPTION
**Pull request by careydayrit**
Removing comment to contact support, CSE can no longer shuffle the salt keys for a WordPress site.

### CODE REVIEW

**Comment by namespacebrian** [comment]
When this is merged, it will show up on customers dashboards as an update for them to apply to their site.  We'll need some language explaining in more detail why this is no longer possible.. people will see it and ask..

**Review by greg-1-anderson — CHANGES_REQUESTED** [review]
Please provide more detail. Customers may need to regenerate their hash values if there was some form of information disclosure, to keep their site secure. If manual intervention via CSE is no longer the way to do this, we will need to find some other way to provide this capability.

**Comment by careydayrit** [comment]
The workaround would be to manually set the values, customers can visit [https://api.wordpress.org/secret-key/1.1/salt/](https://api.wordpress.org/secret-key/1.1/salt/) and replace the values provided by the platform.  The salt can be shuffled without CSE intervention.

**Comment by CdrMarks** [comment]
@greg-1-anderson to code to reset a site's salts was removed in 2018. 
PR: https://github.com/pantheon-systems/titan-mt/pull/16568
Discussion: https://getpantheon.atlassian.net/browse/BUGS-2210

**Comment by scottbuscemi** [comment]
I'm in favor of us moving this forward, but the PR needs to be fixed since there are a lot of other changes/conflicts now included.

**Comment by jazzsequence** [comment]
This PR is super stale and now has even _more_ conflicts.
We should create a ticket in Jira to prioritize this work, pluck the changes from this PR into a clean branch and decide on the relevant changelog update language. @jspellman814 since you're bug wardening this sprint, do you want to own that? I'm happy to create the ticket as well. I think we can leave this PR open until its replacement is pushed (but we could also close this and add the link in the Jira ticket, I defer to @scottbuscemi).

**Comment by jspellman814** [comment]
Yeah, I'll own this @jazzsequence

**Comment by jspellman814** [comment]
Tracking internally as CMSP-221. I've copied this update over to a new PR, #355. Closing this.

**Pull request closed without merging**
