### PR TITLE
Update 4.7

### PR DESCRIPTION
**Pull request by greg-1-anderson**
n.b. Includes the following PRs:

https://github.com/pantheon-systems/WordPress/pull/88
https://github.com/pantheon-systems/WordPress/pull/81

https://pantheon.io/docs/wordpress-4.7-upgrade/

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
"The maximum number of Multidev environment for this service level has been reached." ☹️

**Comment by greg-1-anderson** [comment]
Just manually deleted a few multidevs for now, but eventually we might want to do something similar to the [delete-old-multidevs](https://github.com/pantheon-systems/ci-drops-8/blob/master/scripts/delete-old-multidevs) script in ci-drops-8.

**Comment by greg-1-anderson** [comment]
Most tests passed; just one failure:
```
Then print current URL                                                                            # Behat\MinkExtension\Context\MinkContext::printCurrentUrl()
      │ http://ci-20-ci-wordpress-core.pantheonsite.io/wp-admin/
    And I should be on "/wp-admin/install.php?step=2"                                                 # Behat\MinkExtension\Context\MinkContext::assertPageAddress()
      Current page is "/wp-admin/", but "/wp-admin/install.php" expected. (Behat\Mink\Exception\ExpectationException)
    And I should see "WordPress has been installed."                                                  # Behat\MinkExtension\Context\MinkContext::assertPageContainsText()
```
Seems likely that the install procedure just finished up at a different URL. I'll run through this manually tomorrow and compare. @danielbachhuber does ^^ look familiar to you?

**Comment by danielbachhuber** [comment]
> Seems likely that the install procedure just finished up at a different URL.

Yes, WordPress 4.7 changed the installation UX https://github.com/pantheon-systems/pantheon-wordpress-upstream-tests/commit/c40819a532e21d0d310cfc523d26bf3de6775979

**Comment by greg-1-anderson** [comment]
Thanks for fixing the test failure, @danielbachhuber.

wp-cli 1.0.0 has been deployed to the platform, and ad-hoc testing of 4.7 shows things are working well.  Just need a +1 to deploy.

**Comment by greg-1-anderson** [comment]
git fetch origin
git checkout -b update-4.7 origin/update-4.7

**Comment by ari-gold** [comment]
+1 🚢  :shipit:   🚀

**Pull request merged**
