### PR TITLE
Circle 2 test scripts

### PR DESCRIPTION
**Pull request by greg-1-anderson**
See [ENG-192](https://getpantheon.atlassian.net/browse/ENG-192) for plan.

This implementation forgoes the `test` branch and instead keeps the Circle tests exclusively on the `default` branch. Once this PR is merged, the `default` branch will be set as the default branch for this repo. Any PRs opened against this repo should be made against the default branch (which will be the default behavior if using the GitHub ui).  Note that the [downstream updater script to update WordPress](https://github.com/pantheon-systems/downstream-updater/blob/master/scripts/wp-update-site#L208:L212) now also bases the new WordPress versions off of the default branch.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
One other thing I think I'd like to do here is package the automerge script up into a re-usable component -- perhaps [updatinate](https://github.com/pantheon-systems/updatinate)

**Comment by greg-1-anderson** [comment]
I made a docker container specifically for the merge operation. Originally I did this so that I could sign the commits. I'm not signing the commits yet, but the custom docker container remains.

See the [auto merge script](https://github.com/pantheon-systems/upstream-update-build/blob/1.x/bin/automerge.sh) there.

**Comment by ataylorme** [comment]
@greg-1-anderson the Behat tests in here look great. Well done!

**Comment by greg-1-anderson** [comment]
Thanks for the props, @ataylorme! I agree that these behat tests are awesome -- probably the best I ever stole. Thanks!

**Comment by ataylorme** [comment]
Where did you borrow them from? I would love to see if they have more examples

**Comment by greg-1-anderson** [comment]
These are all from your repository @ataylorme. Top-notch work.

**Comment by greg-1-anderson** [comment]
Oh, my mistake -- these were from @danielbachhuber and @stevector 

https://github.com/pantheon-systems/pantheon-wordpress-upstream-tests/commits/master

**Pull request merged**
