### PR TITLE
Captial P dangit

### PR DESCRIPTION
**Pull request by ataylorme**
Addresses #117

### CODE REVIEW

**Comment by ataylorme** [comment]
Fresh screenshot with the [Twenty Seventeen theme](https://wordpress.org/themes/twentyseventeen/)

**Comment by westonruter** [comment]
`CAPITAL_EVERYTHING_DANGIT()`

**Comment by ataylorme** [comment]
The uppercase `blogname` is coming from the [Twentseventeen theme stylesheet](https://themes.svn.wordpress.org/twentyseventeen/1.2/style.css) (search for `site-title`). 

I can change it but think our screenshot should reflect the theme without modification.

**Comment by westonruter** [comment]
@ataylorme sorry, I was just kidding. Looks good.

**Comment by ataylorme** [comment]
No worries. The dashboard image is quite old so it's probably a good idea to update that as well.

**Comment by greg-1-anderson** [comment]
Deployed with WordPress 4.8

**Pull request merged**
