### PR TITLE
Add circleci context.

### PR DESCRIPTION
**Pull request by kporras07**

### CODE REVIEW

**Comment by jspellman814** [comment]
LGTM, but don't merge this PR. Squash your commits locally, commit --amend your change (or rebase) into the CircleCI commit on the default branch, and then force-push it. [Linking Greg's comment](https://github.com/pantheon-systems/WordPress/pull/310#issuecomment-1021656642) regarding updates to tests for posterity.

**Comment by greg-1-anderson** [comment]
Looks like whichever user is in that context is going to need an ssh key added on Pantheon.

**Comment by kporras07** [comment]
Fixed. @jspellman814 will handle deployment next week. Thanks!

**Comment by jspellman814** [comment]
This change is now included in the [default branch](https://github.com/pantheon-systems/WordPress/commit/7c1222562a4ba7da6e82d35ab97b35673fd1d4cc). Closing.

**Pull request closed without merging**
