### PR TITLE
Wordpress 4.4

### PR DESCRIPTION
**Pull request by greg-1-anderson**
For more information, please see: https://wordpress.org/news/2015/12/clifford/

Instructions to test:

- Create a new WordPress site on Pantheon.
- When site creation is finished, visit dashboard.
- Switch to "git" mode.
- Clone your site locally.
- Apply the files from this PR on top of your local checkout.
  - git remote add wp git@github.com:pantheon-systems/WordPress
  - git fetch wp
  - git merge wp/wordpress-4.4
- Push your files back up to Pantheon.
- Switch back to sftp mode.
- Visit your site. Step through the installation process.
- Confirm that the checksums of all of the core files match:
  - terminus --site=YOURWORDPRESSSITE wp core verify-checksums
  - Should say: "Success: WordPress install verifies against checksums."

### CODE REVIEW

**Comment by aeligature** [comment]
Install looks good but I don't see the twentysixteen theme in here.

**Comment by greg-1-anderson** [comment]
Good catch -- looks like the new theme is not included in the upgrade path.  I will manually add it, and then force-push over this commit.

**Comment by greg-1-anderson** [comment]
Okay, I added twentysixteen; seems okay now.  Please start over (sorry), and see if it checks out this time.

**Comment by aeligature** [comment]
It's now running with twentysixteen.

**Comment by aeligature** [comment]
:+1:

**Pull request merged**
