### PR TITLE
Use custom login_message when present

### PR DESCRIPTION
**Pull request by wonkeythemonkey**
Addresses https://github.com/pantheon-systems/WordPress/issues/192

If a developer has set a custom message for the login screen using `add_filter('login_message', $function);`, it should now display on the customized Pantheon login screen as well.

Merged code does the following:

* Replaces default login text with custom-set login text on the login screen
* Disables the default WP `apply_filter('login_message')` behavior to prevent the message being displayed a second time
* Slightly modifies the display CSS for the login message and Pantheon button to accommodate longer messages

### CODE REVIEW

**Comment by ataylorme** [comment]
Hi Jesse,
Thank you for the pull request! I am currently traveling for WordCamp Miami but hope to be able to test this when I return (after I catch up on email 😉 ).

**Comment by ataylorme** [comment]
Screen Shot 2019-04-01 at 1 58 08 PM

**Comment by wonkeythemonkey** [comment]
Seems fair enough. However, I would suggest that Pantheon's "Login to your Wordpress Site" message be hidden (or at least hideable) as the "Return to Pantheon" button is, since it is part of Pantheon's branding and not part of standard Wordpress.

**Comment by wonkeythemonkey** [comment]
Also, when I set a custom message using the `login_message` filter, there is no pretty block drawn around it in Pantheon environments. It's just dumped out as plain text above the login form.

**Comment by danielbachhuber** [comment]
Thanks again for your work on this, @wonkeythemonkey. I'm landing a `pantheon_wp_login_text` filter in #210

**Pull request closed without merging**
